# Generated by Django 2.2.6 on 2019-11-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('empphone', models.CharField(max_length=12)),
                ('salarly', models.IntegerField()),
            ],
        ),
    ]
