# Generated by Django 2.2.6 on 2019-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapidemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='exp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
