# Generated by Django 2.2.7 on 2019-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=10)),
                ('bookname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
