# Generated by Django 2.2.7 on 2019-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.IntegerField()),
                ('orderdate', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
