# Generated by Django 2.2.6 on 2019-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_loginform_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
