# Generated by Django 2.2.7 on 2019-11-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('empname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
